server:
  port : ${CAFETERIA_USER_PORT:8083}
  servlet:
    context-path: /user
api:
  security:
    token:
      secret: ${JWT_SECRET:cafeteria-key}
spring:
  application:
    name: user
  datasource:
    username: postgres
    password: postgres
    url: ${CAFETERIA_POSTGRES_URL:jdbc:postgresql://localhost:5432/cafeteria}
    hikari:
      pool-name: postgresql-pool
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false




