version: "3.9"

services:
  user:
    image: user
    build:
      context: ../user
      dockerfile: ../user/Dockerfile
    restart: always
    ports:
      - '8083:8083'
  order:
    image: order
    build:
      context: ../order
      dockerfile: ../order/Dockerfile
    restart: always
    ports:
      - '8081:8081'
  product:
    image: product
    build:
      context: ../product
      dockerfile: ../product/Dockerfile
    restart: always
    ports:
      - '8082:8082'
  web:
    image: web
    build:
      context: ../web
      dockerfile: ../web/Dockerfile
    restart: always
    ports:
      - '8080:8080'
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=cafeteria
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db-vol:/var/lib/postgresql/data
      - ../database/00_create_tables.sql:/docker-entrypoint-initdb.d/00_create_tables.sql:ro
      - ../database/01_initialize.sql:/docker-entrypoint-initdb.d/01_initialize.sql:ro
volumes:
  db-vol:
    driver: local

