server:
  port : ${CAFETERIA_WEB_PORT:8080}
  servlet:
    context-path: /
api:
  security:
    token:
      secret: ${JWT_SECRET:cafeteria-key}
spring:
  application:
    name: web
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/cafeteria
    hikari:
      pool-name: postgresql-pool
      connection-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: false

services:
  user-api: ${CAFETERIA_USER_URL:http://localhost:8083/user}
  product-api: ${CAFETERIA_PRODUCT_URL:http://localhost:8082/product}
  order-api: ${CAFETERIA_ORDER_URL:http://localhost:8081/order}




